"""Generate completed medical report as PDF."""
import os
from datetime import date
import fitz


def generate_report_pdf(report: dict, output_dir: str) -> str:
    """Generate a PDF medical report from the completed answers. Returns output path."""
    os.makedirs(output_dir, exist_ok=True)

    doc = fitz.open()
    fontsize = 10
    heading_size = 14
    subheading_size = 12
    margin = 50
    page_width, page_height = 595, 842  # A4

    page = None
    y_pos = page_height  # Force first page creation

    def _new_page():
        nonlocal page, y_pos
        page = doc.new_page(width=page_width, height=page_height)
        y_pos = margin + fontsize

    def _check_space(needed: float):
        nonlocal page, y_pos
        if page is None or y_pos + needed > page_height - margin:
            _new_page()

    def write_line(text: str, fs: float = fontsize, bold: bool = False, indent: float = 0):
        nonlocal y_pos
        _check_space(fs * 1.5)
        page.insert_text(
            fitz.Point(margin + indent, y_pos),
            text[:200],
            fontsize=fs,
            fontname="hebo" if bold else "helv",
        )
        y_pos += fs * 1.5

    def write_wrapped(text: str, fs: float = fontsize, bold: bool = False, indent: float = 0):
        """Write text with basic word wrapping."""
        max_width = page_width - 2 * margin - indent
        chars_per_line = int(max_width / (fs * 0.5))  # rough estimate
        words = text.split()
        line = ""
        for word in words:
            test = f"{line} {word}".strip()
            if len(test) > chars_per_line:
                if line:
                    write_line(line, fs=fs, bold=bold, indent=indent)
                line = word
            else:
                line = test
        if line:
            write_line(line, fs=fs, bold=bold, indent=indent)

    # ── Title page header ──
    _new_page()
    write_line("MEDICAL REPORT", fs=18, bold=True)
    y_pos += 10
    write_line(f"Report Type: {report.get('template_name', 'General')}", fs=subheading_size)
    write_line(f"Generated: {date.today().strftime('%d %B %Y')}", fs=fontsize)
    write_line(f"Report ID: {report.get('id', '')}", fs=fontsize)
    y_pos += 15

    # ── Patient details ──
    write_line("PATIENT DETAILS", fs=subheading_size, bold=True)
    y_pos += 5
    patient = report.get("patient", {})
    for label, key in [
        ("Name", "full_name"),
        ("Date of Birth", "date_of_birth"),
        ("NHS Number", "nhs_number"),
        ("Address", "address"),
        ("GP", "gp_name"),
        ("Practice", "gp_practice"),
    ]:
        val = patient.get(key, "")
        if val:
            write_line(f"{label}: {val}")
    y_pos += 15

    # ── Questions and answers ──
    write_line("REPORT FINDINGS", fs=subheading_size, bold=True)
    y_pos += 10

    for i, answer in enumerate(report.get("answers", []), 1):
        _check_space(60)  # Ensure room for question + answer start
        write_wrapped(f"Q{i}. {answer.get('question_text', '')}", bold=True)
        y_pos += 3

        ans_text = answer.get("answer", "").strip()
        if ans_text:
            write_wrapped(f"A: {ans_text}", indent=15)
        else:
            write_line("A: [No answer provided]", indent=15)

        # Source references
        evidence = answer.get("evidence", [])
        used = [e for e in evidence if e.get("text")]
        if used:
            refs = [f"{e['source_file']} p.{e['page_num'] + 1}" for e in used[:3]]
            write_line(f"Sources: {'; '.join(refs)}", fs=8, indent=15)

        y_pos += 10

    # ── Footer ──
    _check_space(40)
    y_pos += 20
    write_line("─" * 60, fs=8)
    write_line("This report was generated by SAR Redact Medical Reports.", fs=8)
    write_line("The information has been reviewed by the clinician named above.", fs=8)

    output_path = os.path.join(output_dir, f"report_{report['id']}.pdf")
    doc.save(output_path)
    doc.close()
    return output_path
